// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzoPaMji46lhYS1OgWZsx1t2953yRA64c',
    appId: '1:597832403527:web:7be4d2bcb360c7f3bc3f62',
    messagingSenderId: '597832403527',
    projectId: 'e-commerce-772cf',
    authDomain: 'e-commerce-772cf.firebaseapp.com',
    storageBucket: 'e-commerce-772cf.firebasestorage.app',
    measurementId: 'G-E0EPLBFTPS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCECRmqHaMiEo1CkQvuezGpRhBBmmQ32zc',
    appId: '1:597832403527:android:1e1c0eddaf063090bc3f62',
    messagingSenderId: '597832403527',
    projectId: 'e-commerce-772cf',
    storageBucket: 'e-commerce-772cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFj9ziIEaIKCyP3PUC6JlLC36xBA_lnNE',
    appId: '1:597832403527:ios:98e6fc3d840097e7bc3f62',
    messagingSenderId: '597832403527',
    projectId: 'e-commerce-772cf',
    storageBucket: 'e-commerce-772cf.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFj9ziIEaIKCyP3PUC6JlLC36xBA_lnNE',
    appId: '1:597832403527:ios:98e6fc3d840097e7bc3f62',
    messagingSenderId: '597832403527',
    projectId: 'e-commerce-772cf',
    storageBucket: 'e-commerce-772cf.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzoPaMji46lhYS1OgWZsx1t2953yRA64c',
    appId: '1:597832403527:web:33e778828830693cbc3f62',
    messagingSenderId: '597832403527',
    projectId: 'e-commerce-772cf',
    authDomain: 'e-commerce-772cf.firebaseapp.com',
    storageBucket: 'e-commerce-772cf.firebasestorage.app',
    measurementId: 'G-6W8RVG9GDB',
  );
}
